site_name: Teclado
site_url: https://tecladocode.github.io/complete-python-course/
docs_dir: build
theme:
  name: material
  features:
    - navigation.sections
    - navigation.tabs
nav:
  #[[[cog
  #from content import get_grouped_build_sections
  #groups = get_grouped_build_sections()
  #for group in groups:
  #    cog.outl(f"- {group}:")
  #    for section in groups[group]:
  #        cog.outl(f"  - {section['index']['title']}:")
  #        cog.outl(f"    - Section Introduction: {section['index']['path']}")
  #        for lecture in section['lectures']:
  #            if not lecture["hidden"]:
  #                cog.outl(f"    - {lecture['title']}: {lecture['path']}")
  #]]]
  - Practical Python:
    - Async Development with Python:
      - Section Introduction: async_development/README.md
      - Code samples for this section: async_development/code_samples/README.md
  #[[[end]]]
