site_name: The Complete Python Course
docs_dir: build
repo_url: https://github.com/tecladocode/complete-python-course
repo_name: tecladocode/complete-python-course
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - social
  - git-revision-date-localized:
      enable_creation_date: true
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  features:
    - navigation.sections
    - navigation.tabs
    - content.code.annotate
    - content.tooltips
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal

      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
extra:
  analytics:
    provider: custom
    domain: complete-python.teclado.com
  status:
    new: Recently added
nav:
  #[[[cog
  #from content import get_grouped_build_sections
  #groups = get_grouped_build_sections()
  #for group in groups:
  #    cog.outl(f"- {group}:")
  #    for section in groups[group]:
  #        cog.outl(f"  - {section['index']['title']}:")
  #        cog.outl(f"    - Section Introduction: {section['index']['path']}")
  #        for lecture in section['lectures']:
  #            if not lecture["hidden"]:
  #                cog.outl(f"    - {lecture['title']}: {lecture['path']}")
  #]]]
  - Introduction:
      - Course Introduction:
          - Section Introduction: intro/README.md
          - The and & or keywords: intro/and_or/README.md
  #[[[end]]]
